### PR TITLE
Support for Custom Objects/Fields on Repository.addParentFields

### PR DESCRIPTION
**Pull request by jim3692**
I tried to use this library on a custom object, but it doesn't correctly resolve custom lookups.

An example test without my solution can be found on [this branch](https://github.com/jim3692/apex-dml-mocking/tree/custom-object-issue).

The setup is the following:
I have a custom object called `ExampleSObject__c` with a lookup field to `Account`, called `Account__c`.
If I understand correctly, I should be able to query `Account__r.Name` from `ExampleSObject__c` by doing this:
```
repo.addParentFields(
    new SObjectType[] { Account.SObjectType },
    new SObjectField[] { Account.Name }
);
```
However, the resulting query is `SELECT Id, Account.Name FROM ExampleSObject__c`, while it should be `SELECT Id, Account__r.Name FROM ExampleSObject__c`.

Although we could create a map similar to `childToRelationshipNames`, which could contain the parent relationships, there are cases where such a solution can be problematic. Such case is having multiple lookup fields to the same SObject.

### CODE REVIEW

**Comment by jamessimone** [comment]
@jim3692 🤦‍♂️ thanks for submitting this! Can’t believe I didn’t have a custom object test written out for this already — the perils of trying to maintain this code in a few different places has bitten me a few times, so I apologize for the issue. I see you have this PR listed as a draft — let me know when it’s ready to review, and thanks again for submitting.

**Comment by jim3692** [comment]
@jamessimone This was just a showcase of the issue on addParentFields and there are more things to check before merging the fix.

- We should also improve addChildFields to properly handle the multiple-lookup-fields case that I described.
- Should we keep both the old and the new implementations of those functions?
- We probably need to write more tests with Custom Objects in order to find similar issues.

**Comment by jamessimone** [comment]
@jim3692 yes, I agree. In the end there can only be one implementation of each function. I’m happy to fix the issues that you’ve described, and I’ll have the time today to do so. On the other hand, you would be losing out on the chance to be listed as a contributor if I simply close this PR. Happy to have you listed as a contributor if you can trim this down to the addition of the custom object and the failing test - how does that sound?

**Comment by jim3692** [comment]
@jamessimone  I also have time today to work on it. We can merge this one, and I will open a new one for further improvements.

**Comment by jamessimone** [comment]
@jim3692 thanks again for submitting - please see the changes I've made, I think the API should be extremely solid following those changes.

**Pull request merged**
