### PR TITLE
Link opp to inserted account when trying to add an account manually.

### PR DESCRIPTION
**Pull request by elliot41**

### CODE REVIEW

**Review by jamessimone — APPROVED** [review]
LGTM

**Comment by jamessimone** [comment]
@elliot41 FYI - I ended up removing `AccountTrigger.trigger` after merging in your changes. I also applied prettier formatting to the files, and left a clarifying comment in `AccountHandlerTests.cls` which should help to explain my rationale. In general, I think the changes you were recommending - moving the update to the `AFTER` context - where in reality the Account's Id would be available - makes sense, but as this repository is meant to show off the proper way to do unit tests without DML, I didn't want to distract from that.

**Comment by elliot41** [comment]
Ok ok I understand, thanks

**Comment by elliot41** [comment]
Hello James,

Is it possible to add an example of you mock an SOQL query ?

**Comment by elliot41** [comment]
Hello James,

I'm wondering, imagine I have a businesslogicTrigger, that insert an Opportunity.
When I insert the opp via the trigger I see that there is a missing field to perform the insertion.

In my class test, if y use the DMLMock, I won't see that the record has an error at the insertion.

So in that case we loose the correlation between the way it works in the org and in the testclass ? How can you trust your tests if they do not respond the same way as your org does ?

I was thinking that the testclass allow to test if DML operations have errors for example.

I'm sure i'm missing something.

**Comment by jamessimone** [comment]
Hey Elliot, a test that shows an insert error is an integration test; it tests that the Salesforce database does things like checking validation rules, required fields, uniqueness, etc ….

A unit test does not do that. It only tests that the output of your class matches what you would expect, given inputs.

**Comment by elliot41** [comment]
Hum ok ok, when you are on a Salesforce org, how do you organize your unit tests and your integration tests ? You can mix them in a test class ? with sometimes the dmlmock and sometimes with the real dml ?

**Comment by jamessimone** [comment]
That’s an org-dependent answer, I think; you (and your team, if applicable) need to decide what makes sense to you. I’ve worked in orgs where the unit tests and integration tests were in the same test class, and orgs where they were split out into separate classes.

Something that might help — integration tests should primarily be for handler classes. If your code is organized well and comprised of small classes (units), it will help tremendously in removing (or working towards the removal) of having so many integration tests.

**Comment by elliot41** [comment]
Hum hum, I see I see, in the org i'm working on, I think the previous developer well organized the code, with trigger handlers calling small classes containing business logic : 

image


Another question 😄 I see that the Apex Stub Api allow developer to do Dependency Injection too, have you considered to use this api in your mockDml framework ? Maybe you found out that this was not possible or useless ?

For example, in this article, we don't use the soql query to get the discount, we use a stubprovider : 
https://quirkyapex.com/2017/02/19/the-new-apex-stub-api/

**Comment by jamessimone** [comment]
If you’re interested in the stub api, I would recommend checking out my friend @surajp’s [Universal Mock](https://github.com/surajp/universalmock) repo.

My stance on the Stub API is this - I think it’s wildly useful if you have complicated objects whose public APIs have “specific to the unit under test” needs - in other words, returning objects that are tightly coupled to the implementation you’re testing. For SOQL, and DML operations, where the return types are well understood and will never vary, I think using the Stub API is a bit heavy. It requires a bit too much boilerplate (for me, personally).

I would rather use Inversion of Control through the Factory to control how objects are created; given that DML and SOQL are so prevalent in Salesforce code, using this pattern in combination with the Repository pattern and the injected DML object covers the vast majority of times (again, for me, personally) where mocking is required.

In some orgs in the past, I had more specialized mocks - with Lead Conversion, for example - where now I might instead be tempted to use the Stub API.

**Comment by surajp** [comment]
Thanks for the shoutout @jamessimone

**Comment by elliot41** [comment]
Hello James,

Thanks for your answer I will take a look at the UniversalMock repo.

I now understand that we can perform integration tests in our TriggerHandler, but indeed, we don't need to insert real data for our unit test in small business logic class, that result in a huge gain of time in the execution of test classes.

Actually in our project, we use a generic DataFactory from this github repository : https://github.com/benahm/TestDataFactory

I'm wondering if it is possible to add the DML Mock pattern inside of this DataFactory, where we can choose if we want the real dml operations, or the mocking service.

Thanks

**Comment by elliot41** [comment]
Jams, I have another point where I need explanations.

When you perform a DML query with from your Repository Class, at the end you perform the query with this method : 
image

When you are in a Mock context, in the RepoFactoryMock Class you use the "getResult" method : 
image

You perform a for loop on the property "QueryResults", but I can't find where in the code you populate this property ?! 
image


Thanks in advance :)

**Comment by jamessimone** [comment]
@elliot41 if you're looking for an example of how to use the `QueryResults` property, I would advise doing some further reading. I talk quite a bit about this subject on the Joys Of Apex - in [Extendable APIs] (https://www.jamessimone.net/blog/joys-of-apex/extendable-apis/), the [Repository Pattern](https://www.jamessimone.net/blog/joys-of-apex/repository-pattern/) , and [You Need A Strongly Typed Query Builder](https://www.jamessimone.net/blog/joys-of-apex/you-need-a-strongly-typed-query-builder/) . As well, [here's an example of a test from the source code behind those posts](https://github.com/jamessimone/apex-mocks-stress-test/blob/strongly-typed-queries/src/classes/OpportunityUpdater_Tests.cls).

As for your question about the `DMLMock` object, I don't think that it should be coupled to a `TestDataFactory` of any kind - there should be a degree of separation between test setup (test data factories used here), which may involve inserting/updating records as you need to, versus the effects that you expect when testing the public API of the class you have under test (the output for which can be tested through the DML mock).

**Pull request merged**
